name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn tsc
      - name: Check linting
        run: yarn lint:no-cycles
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
        env:
          DB_HOST: test-database-host
          DB_PORT: 27017
          DB_USER: root
          DB_PASSWORD: 123456
          DB_DATABASE: culturale-db
          DB_LOCAL_PORT: 27017
          DB_DOCKER_PORT: 27017
          NODE_LOCAL_PORT: 8080
          NODE_DOCKER_PORT: 8080
          SECRET: culturale-secret
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: coverage
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        env:
            DB_HOST: test-database-host
            DB_PORT: 27017
            DB_USER: root
            DB_PASSWORD: 123456
            DB_DATABASE: culturale-db
            DB_LOCAL_PORT: 27017
            DB_DOCKER_PORT: 27017
            NODE_LOCAL_PORT: 8080
            NODE_DOCKER_PORT: 8080
            SECRET: culturale-secret
        with:
          output: report-markdown
          package-manager: yarn
          test-script: yarn test
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: ${{ steps.coverage.outputs.report }}